server:
  port: 2223
  
spring:
  datasource:    
    url: "jdbc:h2:file:~/test"
    username: "admin"
    password:
    driver-class-name: org.h2.Driver
    platform: h2    
  h2:
    console:
      enabled: true
      path: /h2    
  application:
    name: eurekaclient      

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      instance:
      preferIpAddress: true
